# Generated by Django 5.1.2 on 2026-08-27 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='last_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
